// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim() ?? "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim() ?? "";

export const supabaseConfigError = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY
  ? "Missing Supabase environment variables: set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY."
  : null;

const FALLBACK_URL = "https://missing-supabase-url.invalid";
const FALLBACK_KEY = "missing-supabase-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || FALLBACK_URL,
  SUPABASE_PUBLISHABLE_KEY || FALLBACK_KEY,
  {
    auth: {
      storage: typeof localStorage === "undefined" ? undefined : localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
